Controllers/ComplainController.cs
using Grievancemis.Manager;
using Grievancemis.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Ajax.Utilities;
using System.Web.Services.Description;
using SubSonic.Extensions;



namespace Grievancemis.Controllers
{
    [Authorize]
    [SessionCheckAttribute]
    public class ComplainController : Controller
    {
        // GET: Complain
        private Grievance_DBEntities db = new Grievance_DBEntities();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CaseAssign()
        {
            return View();
        }
        public ActionResult GetCaseAssignGList(FilterModel filtermodel)
        {
            try
            {
                bool IsCheck = false;
                var dt = SP_Model.GetCaseAssignGList(filtermodel);
                if (dt.Rows.Count > 0)
                {
                    IsCheck = true;
                }
                var html = ConvertViewToString("_CaseAssiggnGData", dt);
                var res = Json(new { IsSuccess = IsCheck, Data = html }, JsonRequestBehavior.AllowGet);
                res.MaxJsonLength = int.MaxValue;
                return res;

            }
            catch (Exception ex)
            {
                string er = ex.Message;
                return Json(new { IsSuccess = false, Data = "There are communication error...." }, JsonRequestBehavior.AllowGet); throw;
            }
        }
        public ActionResult GrievanceList()
        {
            return View();
        }
        public ActionResult GetGrievanceList(FilterModel filtermodel)
        {
            try
            {
                bool IsCheck = false;
                var dt = SP_Model.GetGrievanceList(filtermodel);
                if (dt.Rows.Count > 0)
                {
                    IsCheck = true;
                }
                var html = ConvertViewToString("_GrievanceData", dt);
                var res = Json(new { IsSuccess = IsCheck, Data = html }, JsonRequestBehavior.AllowGet);
                res.MaxJsonLength = int.MaxValue;
                return res;

            }
            catch (Exception ex)
            {
                string er = ex.Message;
                return Json(new { IsSuccess = false, Data = "There are communication error...." }, JsonRequestBehavior.AllowGet); throw;
            }
        }

        public ActionResult GetDownGImgDocZip(Guid? grievanceId)
        {
            DataTable dt = SP_Model.GetGrievanceDoc(new FilterModel { GrievanceId = grievanceId.ToString() });
            if (dt.Rows.Count == 0)
            {
                return HttpNotFound("No documents found for the specified grievance.");
            }

            string folderPath = Server.MapPath("~/Doc_Upload");
            string zipFileName = $"{grievanceId}.zip";
            //string zipPath = Path.Combine(folderPath, zipFileName);

            if (!Directory.Exists(Server.MapPath("~/Doc_Upload/ImageZip")))
            {
                Directory.CreateDirectory(Server.MapPath("~/Doc_Upload/ImageZip"));
            }

            // Use a HashSet to track added file names
            HashSet<string> addedFiles = new HashSet<string>();
            var random = new Random();
            int month = random.Next(1, 1200);
            // Define the path for the temporary zip file
            string zipPath = Server.MapPath("~/Doc_Upload/CombinedFilesZip" + month + DateTime.Now.ToDateTimeDDMMYYYY() + ".zip");

            using (var zip = ZipFile.Open(zipPath, ZipArchiveMode.Create))
            {
                foreach (DataRow dr in dt.Rows)
                {
                    string filePath = dr["DocumentPath"].ToString();
                    if (!string.IsNullOrEmpty(filePath))
                    {
                        //string fileName = Path.GetFileName(filePath);
                        //string filePathc = Path.Combine(folderPath, fileName);

                        //// Check if the file has already been added
                        //if (!addedFiles.Contains(fileName) && System.IO.File.Exists(filePathc))
                        //{
                        //    zip.CreateEntryFromFile(filePathc, fileName);
                        //    addedFiles.Add(fileName); // Mark this file as added
                        //}
                        string fileName = Path.GetFileName(filePath);
                        // Add the file to the zip
                        //var file = Directory.GetFiles(filePath, "*.*");
                        string filePathc = Path.Combine(folderPath + "/GID" + grievanceId, fileName);
                        if (!string.IsNullOrWhiteSpace(filePathc) && !string.IsNullOrWhiteSpace(fileName))
                        {
                            zip.CreateEntryFromFile(filePathc, fileName);
                        }
                    }
                }
            }

            byte[] fileBytes = System.IO.File.ReadAllBytes(zipPath);
            System.IO.File.Delete(zipPath); // Clean up the zip file after download

            return File(fileBytes, "application/zip", zipFileName);
        }

        public ActionResult RevertCList()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RevertCPost(FilterModel filterModel)
        {
            try
            {
                if (MvcApplication.CUser == null)
                {
                    return Json(new { success = false, message = "All fileds are required.", Data = 201 });
                }
                if (MvcApplication.CUser.RoleId == "0" || string.IsNullOrWhiteSpace(MvcApplication.CUser.RoleId))
                {
                    return Json(new { success = false, message = "All fileds are required.", Data = 201 });
                }
                //DataTable dtcheck = SP_Model.GetSPCheckRevertAlready();
                //if (dtcheck.Rows.Count > 0)
                //{
                //    return Json(new { success = false, message = "This record is already exists.....", resdata = 1 });
                //}
                string Greid = string.Empty;
                if (filterModel.GrievanceId_fk == Guid.Empty || filterModel.RevertTypeId == 0 || string.IsNullOrWhiteSpace(filterModel.TeamRevertMessage))
                {
                    return Json(new { success = false, message = "All fileds are required.", Data = 0 });
                }
                using (var db = new Grievance_DBEntities())
                {
                    Tbl_TeamRevertComplain teamRevertComplain = new Tbl_TeamRevertComplain();

                    teamRevertComplain.GrievanceId_fk = filterModel.GrievanceId_fk;
                    teamRevertComplain.RevertTypeId = filterModel.RevertTypeId;
                    teamRevertComplain.TeamRevertMessage = filterModel.TeamRevertMessage;
                    teamRevertComplain.TeamRoleId = Convert.ToInt32(MvcApplication.CUser.RoleId);
                    teamRevertComplain.IsActive = true;
                    teamRevertComplain.TeamRevert_Date = DateTime.Now.Date;
                    teamRevertComplain.CreatedBy = MvcApplication.CUser.UserId;
                    teamRevertComplain.CreatedOn = DateTime.Now;

                    db.Tbl_TeamRevertComplain.Add(teamRevertComplain);
                    int res = db.SaveChanges();
                    var tblgrive = db.Tbl_Grievance.Find(filterModel.GrievanceId_fk);
                    tblgrive.RevertType_Id = filterModel.RevertTypeId;
                    tblgrive.RevertTypeDate = DateTime.Now.Date;
                    db.SaveChanges();
                    if (res > 0)
                    {
                        DataTable dt = new DataTable();
                        dt = SP_Model.GetRevartMail(teamRevertComplain.GrievanceId_fk.ToString(), teamRevertComplain.TeamId_pk.ToString());
                        if (dt.Rows.Count > 0)
                        {
                            if (Greid.Length <= 0)
                            {
                                Greid = SP_Model.Usp_GetCIdRevart(dt.Rows[0]["GrievanceId_fk"].ToString()).Rows[0]["CaseId"].ToString();
                            }
                            DataTable dtteamemails = SP_Model.GetTeamMailID();//RolesIdcont.Community
                            res = CommonModel.SendMailRevartPartUser(dtteamemails.Rows[0]["EmailList"].ToString(), dt.Rows[0]["Email"].ToString(), Greid, dt.Rows[0]["Name"].ToString(), dt.Rows[0]["TeamRevertMessage"].ToString(), dt.Rows[0]["RevertStatus"].ToString());
                        }
                        if (res > 0)
                        {
                            teamRevertComplain.TeamIsSent = true;
                            db.SaveChanges();
                            return Json(new { success = true, message = "Data saved and mail sended successfully!", Data = 0 });
                        }
                        else
                        {
                            return Json(new { success = true, message = "Data saved successfully!", Data = 0 });
                        }
                    }
                    else
                    {
                        return Json(new { success = true, message = "Record not Submitted.", Data = 0 });
                    }
                }
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = "An error occurred: " + ex.Message, Data = 0 });
            }
        }
        [HttpPost]
        public ActionResult AssignWork(List<FilterModel> filterModels)
        {
            Grievance_DBEntities db_ = new Grievance_DBEntities();
            // Check if the list is null or empty
            if (filterModels == null || !filterModels.Any())
            {

Views/Complain/CaseAssign.cshtml
@using Grievancemis.Manager
@*@model Grievancemis.Models.AssignTo*@
@model Grievancemis.Models.FilterModel
@{
    ViewBag.Title = "Case Assign";
    ViewBag.SubTitle = "Case Assign";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/fSelect.css" rel="stylesheet" />
<div class="page-header">
    <div class="page-block">
        <div class="page-header-title">
            <h2 class="mb-0">@ViewBag.Title</h2>
            <ul class="breadcrumb">
                @*<li class="breadcrumb-item"><a href="/">Home</a></li>*@
                <li class="breadcrumb-item" aria-current="page">@ViewBag.SubTitle</li>
            </ul>
        </div>
    </div>
</div>

<div class="grievances-list">
    <div class="box-design">
        @using (Html.BeginForm("GetCaseAssignGList", "Complain", FormMethod.Post, new { @id = "formid", @class = "", role = "form", autocomplete = "off", enctype = "multipart/form-data", noValidate = "novalidate" }))
        {
            <div class="flex-row">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.StateId, CommonModel.GetState(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TypeGId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.TypeGId, CommonModel.GetGrievanceType(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TypeGId, "", new { @class = "text-danger" })
                </div>

                <div class="form-btn">
                    <button id="search-button" class="btn btn-primary">Search</button>
                </div>
            </div>
        }
    </div>
</div>

<div id="subdata"></div>

@*------------ Work Assign Model popup ---------------------*@

<div class="modal fade animate" id="workAssignModal" tabindex="-1" role="dialog"
     aria-labelledby="workAssignModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false" aria-modal="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="workAssignModalLabel">Case Assign To Panel Member </h5>
                <button type="button" class="close popup-close" data-dismiss="modal" aria-label="Close">
                    <i class="ti ti-x"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    @Html.HiddenFor(x => x.GrievanceId_fk)
                    <div class="modal-design">
                        <p>
                            Case Id:
                            <span><strong id="assignCaseId"></strong></span>
                        </p>
                        <p>
                            Name:
                            <span><strong id="assignName"></strong></span>
                        </p>
                        <p>
                            Complain Date:
                            <span><strong id="assignCreatedOn"></strong></span>
                        </p>
                    </div>
                   
                    <div class="form-group mar-bom">
                        @Html.LabelFor(model => model.User_Idfk, htmlAttributes: new { @class = "control-label" })
                        <span style="color:red;">*</span>
                        @Html.DropDownList("User_Idfk", CommonModel.GetpanelList(false), new { @class = "form-control choices-multiple", @multiple = "multiple", @required = "required" })
                        @Html.ValidationMessageFor(model => model.User_Idfk, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary popup-close" data-dismiss="modal">Close</button>
                <button type="submit" id="confirmWorkAssign" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {

    @Scripts.Render("~/bundles/jqueryval");
    <script src="~/Content/fSelect.js?v=002"></script>
    <script>
        $(document).ready(function () {
            $('#workAssignModal').modal({
                backdrop: 'static',
                keyboard: false
            });
            bindload();
            //$('#User_Idfk').fSelect();
            $('#search-button').on('click', function (e) {
                e.preventDefault();
                bindload();
            });
            $(document).on('click', '.popup-close', function () {
                $('#workAssignModal').modal('hide');
            });

            $('#confirmWorkAssign').on('click', function () {
                var grievanceId = $('#GrievanceId_fk').val(); // Get the grievance ID
                var User_Idfks = $('#User_Idfk').val(); // Get selected User_Idfk

                // Validation
                if (!User_Idfks || User_Idfks.length === 0) {
                    toastr.error('Please select at least one role');
                    return false;
                }

                // Prepare data for the AJAX request
                var requests = User_Idfks.map(function (uId) {
                    return {
                        Grievance_Idfk: grievanceId,
                        User_Idfk: uId,
                    };
                });

                $.ajax({
                    type: "POST",
                    url: document.baseURI + "/Complain/AssignWork",
                    data: JSON.stringify(requests), // Send as JSON
                    contentType: "application/json; charset=utf-8", // Set content type
                    success: function (response) {
                        if (response.success) {
                            toastr.success(response.message);
                            $('#workAssignModal').modal('hide');
                        } else {
                            toastr.error(response.message);
                        }
                    },
                    error: function (xhr, status, error) {
                        toastr.error("An error occurred: " + error);
                    }
                });
            });

        });
        function openWorkAssignPopup(id, caseId, name, createdOn, UserAspIds) {

            if (id != null && id != '') {
              
                $('#workAssignModal').modal('show');
                $('#workAssignModal').attr('aria-hidden', 'true');
                $('#assignCaseId').html('');
                $('#assignName').html('');
                $('#assignCreatedOn').html('');

                $('#GrievanceId_fk').val(id);
                $('#assignCaseId').html(caseId);
                $('#assignName').html(name);
                $('#assignCreatedOn').html(createdOn);
                if (UserAspIds) {
                    let str = UserAspIds;//'"1ea6f120-698b-4172-81c7-5126d8229dc9","fa207900-0224-4f12-aa80-cec4316bb871"';
                    let AarrayselectedValues = str.replace(/"/g, '').split(',').map(val => `${val}`);
                    //AarrayselectedValues = ["1ea6f120-698b-4172-81c7-5126d8229dc9", "fa207900-0224-4f12-aa80-cec4316bb871"];
                    console.log(AarrayselectedValues);
                    resetAndSetValues('#User_Idfk', AarrayselectedValues);
                }
                else {
                    resetAndSetValues('#User_Idfk', []);
                }
            }
            else {
                window.location.href = document.baseURI + "/Grievnce/GrievanceCaseAdd";
            }
        }
        function resetAndSetValues(selector, valuesArray) {
            const $element = $(selector);
            if ($element) {
                $element.fSelect();
                if (valuesArray) {
                    $element.fSelect('setSelectedValues', valuesArray);
                } else {
                    $element.fSelect('setSelectedValues', []);
                }
            }           
        }
        function setSelectedValues(elementId, valuesArray) {
            // Update the underlying <select> element's value
            $('#' + elementId).val(valuesArray);

            // Refresh the fSelect instance to reflect the new values
            $('#' + elementId).fSelect('reload');
        }

        function bindload() {
            //debugger;
            $("#subdata").html(''); $('#div-download').empty();
            var filtermodel = new Object();
            filtermodel.StateId = $('#StateId').val() == '' ? '' : $('#StateId').val();
            filtermodel.TypeGId = $('#TypeGId').val() == '' ? '' : $('#TypeGId').val();
            // filtermodel.ToDt = $('#ToDt').val() == '' ? '' : $('#ToDt').val();
            $.ajax({
                type: "Get",
                url: document.baseURI + "/Complain/GetCaseAssignGList",
                data: filtermodel,
                //cache: false,
                success: function (res) {
                    if (res.IsSuccess) {
                        $("#subdata").html(res.Data);

                        //if ($.fn.dataTable.isDataTable('#tbl')) {
                        //    $("#tbl").dataTable().fnDestroy();
                        //}
                        //table = $('#tbl').DataTable({
                        //    //scrollY: "400px",
                        //    //scrollX: true,
                        //    //scrollCollapse: true,
                        //    paging: false,
                        //    "dom": '<"pull-left"f><"pull-right"l>tip',
                        //    //"ordering": false,
                        //    // order: [[1,0, 'desc']],
                        //    // pageLength: 100,
                        //    fixedColumns: {
                        //        leftColumns: 1,
                        //        rightColumns: 1
                        //    },
                        //    buttons: [{
                        //        extend: 'excel', text: '<span><i class="fa fa-download"></i> Download</span>', title: 'Participant Lists',//$('#IDDistrict option:selected').text() +
                        //        className: 'btn btn-primary button-icon mr-3 mt-1 mb-1',
                        //        filename: 'Participant Lists',
                        //        exportOptions: { modifier: { page: 'all' } }
                        //    }],
                        //});
                        //$('.dataTables_filter input[type="search"]').css(
                        //    { 'width': '200px', 'display': 'inline-block' }
                        //);
                        //$('#div-download').empty();
                        //table.buttons().container().appendTo($('#div-download'));
                    }
                    else {
                        $("#subdata").html('<h5 class="text-danger">' + res.Data + '</h3>');
                    }
                },
                error: function (req, error) {
                    if (error === 'error') { error = req.statusText; }
                    var errormsg = 'There was a communication error: ' + error;
                    //Do To Message display
                    $("#subdata").html('<h5 class="text-danger">' + errormsg + '</h3>');
                }
            });
        }

    </script>

}

Views/Complain/RevartList.cshtml
@using Grievancemis.Manager
@model Grievancemis.Models.FilterModel
@{
    ViewBag.Title = "Conversation Details";
    ViewBag.SubTitle = "Grievances List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    ul li {
        display: inline-block;
    }

    li {
        float: left;
    }
</style>
<div class="page-header">
    <div class="page-block">
        <div class="page-header-title">
            <h2 class="mb-0">@ViewBag.Title</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/Complain/GrievanceList">@ViewBag.SubTitle</a></li>
                <li class="breadcrumb-item" aria-current="page">@ViewBag.Title</li>
            </ul>
        </div>
    </div>
</div>

<div class="box-design">
    @using (Html.BeginForm("GetRevartList", "Complain", FormMethod.Post, new { @id = "formid", @class = "", role = "form", autocomplete = "off", enctype = "multipart/form-data", noValidate = "novalidate" }))
    {
        @Html.HiddenFor(x => x.GrievanceId)
        <div class="flex-row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.StateId, CommonModel.GetState(), null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.TypeGId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.TypeGId, CommonModel.GetGrievanceType(), null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TypeGId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.RevertTypeId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.RevertTypeId, CommonModel.GetMasterRevertType(1), null, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RevertTypeId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-btn">
                <button id="search-button" class="btn btn-primary">Search</button>
            </div>
        </div>
    }
</div>
<div class="table-box">
    <div id="subdata"></div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            bindload();
            $('#search-button').on('click', function (e) {
                e.preventDefault();
                bindload();
            });

        });
        function bindload() {
            debugger;
            $("#subdata").html(''); $('#div-download').empty();
            var filtermodel = new Object();
            filtermodel.StateId = $('#StateId').val() == '' ? '' : $('#StateId').val();
            filtermodel.TypeGId = $('#TypeGId').val() == '' ? '' : $('#TypeGId').val();
            filtermodel.RevertTypeId = $('#RevertTypeId').val() == '' ? 0 : $('#RevertTypeId').val();
            filtermodel.GrievanceId = $('#GrievanceId').val() == '' ? '' : $('#GrievanceId').val();
            $.ajax({
                type: "Get",
                url: document.baseURI + "/Complain/GetRevartList",
                data: filtermodel,
                //cache: false,
                success: function (res) {
                    if (res.IsSuccess) {
                        $("#subdata").html(res.Data);

                        if ($.fn.dataTable.isDataTable('#tbl')) {
                            $("#tbl").dataTable().fnDestroy();
                        }
                        table = $('#tbl').DataTable({
                            scrollY: "400px",
                            scrollX: true,
                            scrollCollapse: true,
                           // paging: false,
                            "dom": '<"pull-left"f><"pull-right"l>tip',
                            //"ordering": false,
                            // order: [[1,0, 'desc']],
                             pageLength: 25,
                            fixedColumns: {
                                leftColumns: 1,
                                rightColumns: 1
                            },
                            buttons: [{
                                extend: 'excel', text: '<span><i class="fa fa-download"></i> Download</span>', title: 'Participant Lists',//$('#IDDistrict option:selected').text() +
                                className: 'btn btn-primary button-icon mr-3 mt-1 mb-1',
                                filename: 'Participant Lists',
                                exportOptions: { modifier: { page: 'all' } }
                            }],
                        });
                        //$('.dataTables_filter input[type="search"]').css(
                        //    { 'width': '200px', 'display': 'inline-block' }
                        //);
                        //$('#div-download').empty();
                        //table.buttons().container().appendTo($('#div-download'));
                    }
                    else {
                        $("#subdata").html('<h5 class="text-danger">' + res.Data + '</h3>');
                    }
                },
                error: function (req, error) {
                    if (error === 'error') { error = req.statusText; }
                    var errormsg = 'There was a communication error: ' + error;
                    //Do To Message display
                    $("#subdata").html('<h5 class="text-danger">' + errormsg + '</h3>');
                }
            });
        }
    </script>
}

Views/Complain/_ComData.cshtml
@model DataTable
@using System.Data

<div class="grievances-list">
    @*<h2>Revert Complain List</h2>*@
    <table class="table table-bordered table-hover dt-responsive display tbl" id="tbl" width="100%">
        <thead>
            <tr>
                <th>Serial No</th> <!-- Added Serial No column -->
                <th>Case Id</th>
                <th>Complain<br /> Date</th>
                <th>Name</th>
                <th>Status</th>
                <th>Revert Date</th>
                <th>Team Message</th>
                <th>Team <br />Reported By</th>
                <th>User Revert<br /> Date</th>
                <th>User Revert<br /> Message</th>


            </tr>
        </thead>
        <tbody>
            @{
                if (Model.Rows.Count > 0)
                {
                    int serialNo = 1; // Initialize the serial number
                    foreach (DataRow row in Model.Rows)
                    {
                        <tr>
                            <td>@serialNo</td> <!-- Display the serial number -->
                            <td>@row["CaseId"]</td>
                            <td style="word-wrap:break-word;">@row["ComDate"]</td>
                            <td>@row["Name"]</td>
                            <td>@row["RevertStatus"]</td>
                            <td>@row["RevartDate"]</td>
                            <td>@row["TeamRevertMessage"]</td>
                            <td>@row["TeamReportedByName"]</td>
                            <td>@row["UserRevartDate"]</td>
                            <td>@row["UserRevertMessage"]</td>
                        </tr>
                        serialNo++; // Increment the serial number
                    }
                }
                else
                {
                    <tr>
                        <td colspan="10" class="text-danger">Record is not found </td>
                    </tr>
                }

            }


        </tbody>
    </table>
</div>