Controllers/MasterController.cs
using Grievancemis.Manager;
using Grievancemis.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Grievancemis.Controllers
{
    public class MasterController : Controller
    {
        // GET: Master
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserDetaillist()
        {
            RegisterViewModel model = new RegisterViewModel();
            return View(model);
        }
        public ActionResult GetUserDetailData(int? RoleId, int CheckBox = 0)
        {
            try
            {
                RoleId = RoleId == null ? 0 : RoleId;
                bool IsCheck = false;
                var tbllist = SP_Model.SPGetUserlist(RoleId);
                if (tbllist != null)
                {
                    IsCheck = true;
                }
                if (CheckBox == 1)
                {
                    var html1 = ConvertViewToString("_UserDetailMPData", tbllist);
                    var res1 = Json(new { IsSuccess = IsCheck, Data = html1 }, JsonRequestBehavior.AllowGet);
                    res1.MaxJsonLength = int.MaxValue;
                    return res1;
                }
                var html = ConvertViewToString("_UserDetailData", tbllist);
                var res = Json(new { IsSuccess = IsCheck, Data = html }, JsonRequestBehavior.AllowGet);
                res.MaxJsonLength = int.MaxValue;
                return res;

            }
            catch (Exception ex)
            {
                string er = ex.Message;
                return Json(new { IsSuccess = false, Data = "" }, JsonRequestBehavior.AllowGet); throw;
            }
        }

        private string ConvertViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (StringWriter writer = new StringWriter())
            {
                ViewEngineResult vResult = ViewEngines.Engines.FindPartialView(ControllerContext, viewName);
                ViewContext vContext = new ViewContext(this.ControllerContext, vResult.View, ViewData, new TempDataDictionary(), writer);
                vResult.View.Render(vContext, writer);
                return writer.ToString();
            }
        }

    }
}

Views/Master/UserDetaillist.cshtml
@model Grievancemis.Models.RegisterViewModel
@{
    ViewBag.Title = "List Of User Details";
    ViewBag.TitleIcon = "fa fa-user";
    ViewBag.SemiTitle = "User Registration";
    ViewBag.SemiTitleLink = "/Account/Register";
}

<style>
    #page-content {
        padding: 0px !important;
    }
</style>

<div class="page-header">
    <div class="page-block">
        <div class="page-header-title">
            <h2 class="mb-0">@ViewBag.Title</h2>
            <ul class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                @*<li class="breadcrumb-item"><a href="javascript: void(0)">Dashboard</a></li>*@
                <li class="breadcrumb-item" aria-current="page">@ViewBag.title</li>
            </ul>
        </div>
    </div>
</div>
<div id="page-content" class="mr-up">
    <div class="container-fluid">
        <div class="row mt-20">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card card-box p-0">
                    @*<div class="card-head">
                            <div class="title">
                                <i class="fa fa-list spacerright2"></i> @ViewBag.Title
                            </div>
                            <div class="tools">
                                <div id="div-download"></div>
                            </div>
                        </div>*@
                    <div class="card-body">
                        <div class="row">
                            <div class="col-xs-12 col-md-12">
                                @using (Html.BeginForm("GetUserDetailData", "Master", FormMethod.Post, new { id = "submission-form" }))
                                {
                                    <div id="submission-data">
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   
    

    <script>
        $(document).ready(function () {
            BindData();
        });

        function BindData() {
            $('#submission-data').removeClass("text-danger");
            var url = $('#submission-form').attr("action");
            var formData = $('#submission-form').serialize();
            $.ajax({
                url: url,
                type: "Post",
                data: '',//{ 'District': District, 'Block': Block },
                success: function (resp) {
                    if (resp.IsSuccess) {
                        $('#submission-data').html(resp.Data);
                        if ($.fn.dataTable.isDataTable('#DataList')) {
                            $("#DataList").dataTable().fnDestroy();
                        }
                        table = $('#DataList').DataTable({
                            //scrollY: "400px",
                            //scrollX: true,
                            //scrollCollapse: true,
                            //paging: false,
                            pageLength: 100,
                            fixedColumns: {
                                leftColumns: 1,
                                rightColumns: 1
                            },
                            buttons: [{
                                extend: 'excel', text: '<span><i class="fa fa-download"></i>Export</span>', title: 'User Lists',//$('#IDDistrict option:selected').text() +
                                className: 'btn btn-primary button-icon mr-3 mt-1 mb-1',
                                filename: 'User List',
                                exportOptions: { modifier: { page: 'all' } }
                            }],
                        });
                        $('.dataTables_filter input[type="search"]').css(
                            { 'width': '500px', 'display': 'inline-block' }
                        );
                        $('#div-download').empty();
                        table.buttons().container().appendTo($('#div-download'));
                    }
                    else {
                        $('#submission-data').html("Record Not Found !!");//TO DO
                        $('#submission-data').addClass("text-danger");//TO DO
                    }
                },
                error: function (req, error) {
                    if (error === 'error') { error = req.statusText; }
                    var errormsg = 'There was a communication error: ' + error;
                    $('#submission-data').html(errormsg);
                }
            });
        }

    </script>
}

Views/Master/_UserDetailData.cshtml
@using System.Data
@{
    ViewBag.Title = "User List";
    DataTable dt = new DataTable();
    if (Model != null)
    {
        dt = Model;
    }
}

<div class="table-responsive">
    <table class="table table-striped nowrap table-bordered dataTable exampleDatatable no-footer" id="DataList">
        <thead>
            <tr>
                <th>SrNo.</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone No</th>
                <th>Role</th>
                @*<th>Modify</th>*@
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @{
                int sno = 1;
                if (Model != null)
                {
                    foreach (DataRow dr in dt.Rows)
                    {
                        <tr>
                            <td class="text-left">@(sno++)</td>
                            <td class="text-left">@dr["Name"]</td>
                            <td class="text-left">@dr["Email"]</td>
                            <td class="text-left">@dr["PhoneNumber"]</td>
                            <td class="text-left"><strong class="badge bg-warning-500/10 fnsz">@dr["Role"]</strong></td>
                            @*<td title="Edit">
                                <a href="~/Account/Register?id=@dr["Id"]" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                            </td>*@
                            @if (dr["LockoutEnabled"].ToString() == "False")
                            {
                                <td title="Disable">
                                    <a href="~/Account/Register_Enable?id=@dr["Id"]" class="btn btn-danger btn-sm"><i class="fa fa-slack"></i></a>
                                </td>
                            }
                            else
                            {
                                <td title="Enabled">
                                    <a href="~/Account/Register_Lock?id=@dr["Id"]" class="btn btn-success btn-sm"><i class="fa fa-check"></i></a>
                                </td>
                            }

                            @*<td class="text-center"><a href="return javascript:void(0);" data-target="#largeModal" data-toggle="modal" onclick="BindEdit('@item.ID', '@item.Name', '@item.Description', '@item.DisplayOrder', this)" title="Edit"><i class="fa fa-edit"></i></a></td>*@
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="9" class="text-danger"><strong> Record Not Found !!</strong></td></tr>
                }
            }

        </tbody>
    </table>
</div>