Controllers/GrievnceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime.Tree;
using Grievancemis.Helpers;
using Grievancemis.Manager;
using Grievancemis.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Newtonsoft.Json;
using static Grievancemis.Manager.CommonModel;

namespace Grievancemis.Controllers
{

    public class GrievnceController : Controller
    {
        private Grievance_DBEntities db = new Grievance_DBEntities();
        // GET: Grievnce

        private const string XsrfKey = "XsrfId";

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        // private RoleManager _userManager;
        public GrievnceController()
        {
        }

        public GrievnceController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GrievanceCaseAdd()
        {
            AuthenticationManager.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return View();
        }
        [HttpPost]
        public ActionResult GrievanceCaseAdd(GrivanceModel grievanceModel)
        {
            try
            {
                int res = 0; System.Text.StringBuilder str = new System.Text.StringBuilder(); string partymail = string.Empty, Greid = string.Empty, stGuid = string.Empty;
                if (ModelState.IsValid)
                {
                    DataTable dtcheck = SP_Model.GetSPCheckGrievanceAlready(grievanceModel.Email.Trim(), DateTime.Now.Date.ToDateTimeyyyyMMdd());
                    if (dtcheck.Rows.Count > 0)
                    {
                        return Json(new { success = false, message = "This record is already exists.....", resdata = 1 });
                    }
                    using (var db = new Grievance_DBEntities())
                    {

                        Tbl_Grievance tbl_Grievance = new Tbl_Grievance
                        {
                            Id = Guid.NewGuid(),
                            Email = grievanceModel.Email,
                            Name = grievanceModel.Name,
                            PhoneNo = grievanceModel.PhoneNo,
                            Gender = grievanceModel.Gender,
                            GrievanceType = grievanceModel.GrievanceType,
                            StateId = grievanceModel.StateId,
                            //Location = grievanceModel.Location,
                            Other = grievanceModel.Other,
                            //Title = grievanceModel.Title,
                            ComplainRegDate = DateTime.Now.Date,
                            Grievance_Message = grievanceModel.GrievanceMessage,
                            IsConsent = grievanceModel.IsConsent,
                            IsActive = true,
                            CreatedOn = DateTime.Now
                        };
                        var igtype = 0; var istype = 0;
                        igtype = Convert.ToInt32(tbl_Grievance.GrievanceType);
                        istype = Convert.ToInt32(tbl_Grievance.StateId);
                        var GType = db.M_GrievanceType.Where(b => b.Id == igtype)?.FirstOrDefault();
                        var SType = db.m_State_Master.Where(b => b.LGD_State_Code == istype)?.FirstOrDefault();

                        stGuid = Convert.ToString(tbl_Grievance.Id);
                        // Handle file upload
                        var URLPath = string.Empty;
                        if (grievanceModel.DocUpload != null && grievanceModel.DocUpload.ContentLength > 0)
                        {
                            FileModel modelfile = CommonModel.saveFile(grievanceModel.DocUpload, "GID" + stGuid, tbl_Grievance.Id.ToString() + DateTime.Now.Date.ToDateTimeDDMMYYYY());
                            string fileExtension = Path.GetExtension(grievanceModel.DocUpload.FileName).ToLower();

                            // Check if the file extension is allowed
                            if (fileExtension == ".zip" || fileExtension == ".png" || fileExtension == ".jpg" || fileExtension == ".pdf" || fileExtension == ".doc" || fileExtension == ".jpeg")
                            {
                                if (modelfile.IsvalidFile)
                                {
                                    URLPath = modelfile.FilePathFull;
                                }
                                else
                                {
                                    return Json(new { success = false, message = "File size is too large. Only files up to 20MB are allowed." });
                                }
                            }
                            else
                            {
                                return Json(new { success = false, message = "Invalid file extension. Only zip, png, jpg, pdf, doc, and jpeg files are allowed." });
                            }

                            // Save the file paths in the Tbl_Grievance table
                            tbl_Grievance.DocUpload = URLPath;

                            // Save the file paths in the Tbl_Grievance_Documents table
                            Tbl_Grievance_Documents tbl_Grievance_Documents = new Tbl_Grievance_Documents
                            {
                                GrievanceId = tbl_Grievance.Id,
                                DocumentPath = URLPath,
                                IsActive = true,
                                CreatedOn = DateTime.Now
                            };
                            db.Tbl_Grievance_Documents.Add(tbl_Grievance_Documents);
                        }

                        db.Tbl_Grievance.Add(tbl_Grievance);
                        res = db.SaveChanges();

                        partymail = tbl_Grievance.Email.Trim();
                        Greid = Convert.ToString(tbl_Grievance.CaseId);
                        if (!string.IsNullOrWhiteSpace(stGuid))
                        {
                            Greid = SP_Model.Usp_GetCaseIDwithguid(stGuid).Rows[0]["CaseId"].ToString();
                        }
                        //str.Append("<table border='1'>");
                        //str.Append("<tr><td>Gender</td><td>" + tbl_Grievance.Gender + "</td></tr>");
                        //str.Append("<tr><td>Email</td><td>Name</td><td>Phone Number</td></tr>");
                        //str.Append("<tr><td>" + tbl_Grievance.Email + "</td><td>" + tbl_Grievance.Name + "</td><td>" + tbl_Grievance.PhoneNo + "</td></tr>");
                        //str.Append("<tr><td>Grievance Type</td><td>State Name</td><td>Title</td></tr>");
                        //str.Append("<tr><td>" + GType.GrievanceType + "</td><td>" + SType.StateName + "</td><td>" + tbl_Grievance.Title + "</td></tr>");
                        //str.Append("<tr><td>Other</td><td colspan='2'>Message</td></tr>");
                        //str.Append("<tr><td>" + tbl_Grievance.Other + "</td><td colspan='2'>" + tbl_Grievance.Grievance_Message + "</td></tr>");
                        //str.Append("</table>");
                    }

                    if (res > 0)
                    {
                        var asp = db.AspNetUsers.Where(x => x.Email == grievanceModel.Email.Trim())?.FirstOrDefault();
                        if (asp != null)
                        {
                            asp.Name = !string.IsNullOrWhiteSpace(grievanceModel.Name) ? grievanceModel.Name.Trim() : string.Empty;
                            asp.PhoneNumber = !string.IsNullOrWhiteSpace(grievanceModel.PhoneNo) ? grievanceModel.PhoneNo.Trim() : string.Empty;
                            db.SaveChanges();
                        }
                        DataTable dt = new DataTable();
                        dt = SP_Model.GetTeamMailID();
                        if (dt.Rows.Count > 0)
                        {
                            Session["EmailId"] = grievanceModel.Email.Trim();
                            res = CommonModel.SendSucessfullMailForUserTeam(dt.Rows[0]["EmailList"].ToString(), str.ToString(), partymail, Greid, CaseOfStatus.NewCase);
                            res = CommonModel.SendMailPartUser(partymail, Greid, grievanceModel.Name, CaseOfStatus.NewCase);
                        }
                        if (res > 0)
                        {
                            return Json(new { success = true, message = "Your request is registered with Grievance reference id : " + Greid + "<br />" + "Mail sended successfully!", res = 1 });//Data saved and mail sended successfully!
                        }

Views/Grievnce/GrievanceList.cshtml
@using Grievancemis.Manager
@model Grievancemis.Models.FilterModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="grievances-list">
    <h2>Grievances List</h2>
    @using (Html.BeginForm("GetGrievanceList", "Grievnce", FormMethod.Post, new { @id = "formid", @class = "", role = "form", autocomplete = "off", enctype = "multipart/form-data", noValidate = "novalidate" }))
    {
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.StateId, CommonModel.GetState(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.TypeGId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.TypeGId, CommonModel.GetGrievanceType(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TypeGId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <button id="search-button" class="btn btn-primary">Search</button>
            </div>
        </div>
    }
</div>
<div id="subdata"></div>
<div class="modal fade" id="progressModal" tabindex="-1" role="dialog" aria-labelledby="progressModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="progressModalLabel">Revart Process</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    @Html.HiddenFor(x=>x.GrievanceId_fk)
                    <label for="cname">Name:</label>
                    <strong id="cname"></strong>
                    <br />
                    <label for="con">Complain Date :</label>
                    <strong id="con"></strong>
                    <br />
                    <label for="CId">Case Id :</label>
                    <strong id="CId"></strong>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.RevertTypeId, htmlAttributes: new { @class = "control-label" })
                            <span style="color:red;">*</span>
                            @Html.DropDownListFor(model => model.RevertTypeId, CommonModel.GetRevertType(), null, new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.RevertTypeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.TeamRevertMessage, htmlAttributes: new { @class = "control-label col-md-2" })
                            <span style="color:red;">*</span>
                            <div class="col-md-10">
                                @Html.TextAreaFor(model => model.TeamRevertMessage, new { @class = "form-control-input", style = "height:100px;", rows = 5 })
                                @Html.ValidationMessageFor(model => model.TeamRevertMessage, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <!-- Revert Option Dropdown -->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="confirm-progress">Submit</button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        $(document).ready(function () {
            bindload();
            $('#progressModal').modal({
                backdrop: 'static',  // Prevent closing when clicking outside the modal
                keyboard: false      // Prevent closing using the escape key
            });
            $('.close, .btn-secondary').on('click', function () {
                $('#progressModal').modal('hide');
            });
            $('#search-button').on('click', function (e) {
                e.preventDefault();
                bindload();
            });
            $('#confirm-progress').on('click', function () {
                PostData();
            });
        });
            // Handle progress button click
            //$(document).on('click', '.progress-button', function () {
            //    $('#progressModal').modal('show');
            //});

    function PostData() {
        var filterModel = {
            GrievanceId_fk: $('#GrievanceId_fk').val(),
            RevertTypeId: $('#RevertTypeId').val(),
            TeamRevertMessage: $('#TeamRevertMessage').val()
        };

        $.ajax({
            type: "POST",
            url: document.baseURI + "/Grievnce/RevertCPost",
            data: filterModel,
            success: function (response) {
                if (response.success) {
                    toastr.success(response.message);
                    $('#progressModal').modal('hide');
                } else {
                    toastr.error(response.message);
                }
            },
            error: function (xhr, status, error) {
                toastr.error("An error occurred: " + error);
            }
        });
    }
    function POPDisplay(id, caseid, name, CreatedOn) {
            $('#GrievanceId_fk').val(id);
            $('#cname').html(name);
        $('#CId').html(caseid);
            $('#con').html(CreatedOn);
            $('#progressModal').modal('show');

        }

        function bindload() {
            debugger;
            $("#subdata").html(''); $('#div-download').empty();
            var filtermodel = new Object();
            filtermodel.StateId = $('#StateId').val() == '' ? '' : $('#StateId').val();
            filtermodel.FromDt = $('#TypeGId').val() == '' ? '' : $('#TypeGId').val();
            // filtermodel.ToDt = $('#ToDt').val() == '' ? '' : $('#ToDt').val();
            $.ajax({
                type: "Get",
                url: document.baseURI + "/Grievnce/GetGrievanceList",
                data: filtermodel,
                //cache: false,
                success: function (res) {
                    if (res.IsSuccess) {
                        $("#subdata").html(res.Data);

                        //if ($.fn.dataTable.isDataTable('#tbl')) {
                        //    $("#tbl").dataTable().fnDestroy();
                        //}
                        //table = $('#tbl').DataTable({
                        //    //scrollY: "400px",
                        //    //scrollX: true,
                        //    //scrollCollapse: true,
                        //    paging: false,
                        //    "dom": '<"pull-left"f><"pull-right"l>tip',
                        //    //"ordering": false,
                        //    // order: [[1,0, 'desc']],
                        //    // pageLength: 100,
                        //    fixedColumns: {
                        //        leftColumns: 1,
                        //        rightColumns: 1
                        //    },
                        //    buttons: [{
                        //        extend: 'excel', text: '<span><i class="fa fa-download"></i> Download</span>', title: 'Participant Lists',//$('#IDDistrict option:selected').text() +
                        //        className: 'btn btn-primary button-icon mr-3 mt-1 mb-1',
                        //        filename: 'Participant Lists',
                        //        exportOptions: { modifier: { page: 'all' } }
                        //    }],
                        //});
                        //$('.dataTables_filter input[type="search"]').css(
                        //    { 'width': '200px', 'display': 'inline-block' }
                        //);
                        //$('#div-download').empty();
                        //table.buttons().container().appendTo($('#div-download'));
                    }
                    else {
                        $("#subdata").html('<h5 class="text-danger">' + res.Data + '</h3>');
                    }
                },
                error: function (req, error) {
                    if (error === 'error') { error = req.statusText; }
                    var errormsg = 'There was a communication error: ' + error;
                    //Do To Message display
                    $("#subdata").html('<h5 class="text-danger">' + errormsg + '</h3>');
                }
            });
        }
</script>
}

Views/Grievnce/RevartList.cshtml
@using Grievancemis.Manager
@model Grievancemis.Models.RevertComplaint
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("GetGrievanceList", "Grievnce", FormMethod.Post, new { @id = "formid", @class = "", role = "form", autocomplete = "off", enctype = "multipart/form-data", noValidate = "novalidate" }))
{
    @*<div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.StateId, CommonModel.GetState(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.LabelFor(model => model.TypeGId, htmlAttributes: new { @class = "control-label" })
                    <span style="color:red;">*</span>
                    @Html.DropDownListFor(model => model.TypeGId, CommonModel.GetGrievanceType(), null, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(model => model.TypeGId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-3">
                <button id="search-button" class="btn btn-primary">Search</button>
            </div>
        </div>*@
}
</div>
<div id="subdata"></div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            bindload();
        });
        function bindload() {
            debugger;
            $("#subdata").html(''); $('#div-download').empty();
            var RevertComplaint = new Object();
            //filtermodel.StateId = $('#StateId').val() == '' ? '' : $('#StateId').val();
            //filtermodel.FromDt = $('#TypeGId').val() == '' ? '' : $('#TypeGId').val();
            // filtermodel.ToDt = $('#ToDt').val() == '' ? '' : $('#ToDt').val();
            $.ajax({
                type: "Get",
                url: document.baseURI + "/Grievnce/GetRevartList",
                data: RevertComplaint,
                //cache: false,
                success: function (res) {
                    if (res.IsSuccess) {
                        $("#subdata").html(res.Data);

                        //if ($.fn.dataTable.isDataTable('#tbl')) {
                        //    $("#tbl").dataTable().fnDestroy();
                        //}
                        //table = $('#tbl').DataTable({
                        //    //scrollY: "400px",
                        //    //scrollX: true,
                        //    //scrollCollapse: true,
                        //    paging: false,
                        //    "dom": '<"pull-left"f><"pull-right"l>tip',
                        //    //"ordering": false,
                        //    // order: [[1,0, 'desc']],
                        //    // pageLength: 100,
                        //    fixedColumns: {
                        //        leftColumns: 1,
                        //        rightColumns: 1
                        //    },
                        //    buttons: [{
                        //        extend: 'excel', text: '<span><i class="fa fa-download"></i> Download</span>', title: 'Participant Lists',//$('#IDDistrict option:selected').text() +
                        //        className: 'btn btn-primary button-icon mr-3 mt-1 mb-1',
                        //        filename: 'Participant Lists',
                        //        exportOptions: { modifier: { page: 'all' } }
                        //    }],
                        //});
                        //$('.dataTables_filter input[type="search"]').css(
                        //    { 'width': '200px', 'display': 'inline-block' }
                        //);
                        //$('#div-download').empty();
                        //table.buttons().container().appendTo($('#div-download'));
                    }
                    else {
                        $("#subdata").html('<h5 class="text-danger">' + res.Data + '</h3>');
                    }
                },
                error: function (req, error) {
                    if (error === 'error') { error = req.statusText; }
                    var errormsg = 'There was a communication error: ' + error;
                    //Do To Message display
                    $("#subdata").html('<h5 class="text-danger">' + errormsg + '</h3>');
                }
            });
        }
    </script>
}